### ISSUE TITLE
我测试你的代码，数据库连接一段时间后就连接不上了。接口请求后，执行到数据库操作的时候就卡住了。

### ISSUE THREAD

**Issue by aohanhongzhi** [feihua/axum-admin#1]
数据库是mysql，应该没问题。

![image](https://github.com/feihua/axum-admin/assets/37319319/dae6cf3d-f554-4f05-9707-6fed6d76a7e4)

**Comment by feihua** [comment]
依赖有升级不

**Comment by aohanhongzhi** [comment]
> 依赖有升级不

没有，就改了数据库，我确定golang连接这个数据库没有问题，数据库也是默认配置。没啥修改。

**Comment by feihua** [comment]
> > 依赖有升级不
> 
> 没有，就改了数据库，我确定golang连接这个数据库没有问题，数据库也是默认配置。没啥修改。

今天有空闲下来测了下，没问题，我现在把项目依赖升级了一下，可以拉下最新代码看看

**Comment by aohanhongzhi** [comment]
我定位出来原因了。没有使用数据库连接池，每次都是新建连接。
![image](https://github.com/feihua/axum-admin/assets/37319319/427b3224-1ad7-4570-84cf-a850bfa5032c)

**Comment by feihua** [comment]
用命令SHOW PROCESSLIST 看下数据库的连接情况，是不是只有这个应用连接上的

**Comment by aohanhongzhi** [comment]
@feihua 上图可以看出来，我就是用了`SHOW PROCESSLIST `分析出来了。

**Comment by aohanhongzhi** [comment]
<img width="938" alt="image" src="https://github.com/feihua/axum-admin/assets/37319319/8cc6736a-0e4c-46a3-8dec-6b94deffb4ff">

# 启动程序，发起请求。

<img width="938" alt="image" src="https://github.com/feihua/axum-admin/assets/37319319/95539b0f-c6d1-4098-a1dc-c63674972aa9">


<img width="938" alt="image" src="https://github.com/feihua/axum-admin/assets/37319319/fc8d34dc-bf1c-4dd7-baaa-537e9281f487">

每个请求，就增加三个，一直到10个。基本上确定程序连接池没有问题。

**Comment by aohanhongzhi** [comment]
我修改了连接池大小
```rust
use std::time::Duration;
use rbatis::rbatis::RBatis;

pub async fn init_db() -> RBatis {
    let rb = RBatis::new();
    rb.init(rbdc_mysql::driver::MysqlDriver {}, "mysql://**:**@*****:3306/test").unwrap();
    let pool = rb.get_pool().unwrap();
    pool.set_max_open_conns(3).await;
    pool.set_max_idle_conns(3).await; // 这个参数设置有效果
    let five_seconds = Duration::new(120, 0); // 设置貌似没有效果啊，官方解答目前不支持
    pool.set_conn_max_lifetime(Option::from(five_seconds)).await;
    return rb;
}
```

数据库连接确实只有3个了。但是过段时间后，还是会出现连接不上的情况。

![image](https://github.com/feihua/axum-admin/assets/37319319/40e42866-caac-4dca-b186-a1a1183d3a69)

**Comment by aohanhongzhi** [comment]
![image](https://github.com/feihua/axum-admin/assets/37319319/9169e85f-4f05-4ea7-b52a-dfbef72bfcfa)

**Comment by aohanhongzhi** [comment]
经过更换数据库连接池，应该解决了。

https://github.com/importcjj/mobc

```rust
use std::time::Duration;
use rbatis::rbatis::RBatis;

use rbdc_pool_mobc::MobcPool;

pub async fn init_db() -> RBatis {
    let rb = RBatis::new();
    let opts = rbdc_mysql::options::MySqlConnectOptions::new()
        .host("****")
        .username("rust")
        .password("*****")
        .database("test");
    rb.init_option::<rbdc_mysql::driver::MysqlDriver, rbdc_mysql::options::MySqlConnectOptions, MobcPool>(rbdc_mysql::driver::MysqlDriver {}, opts).unwrap();


    let pool = rb.get_pool().unwrap();
    pool.set_max_open_conns(2).await;
    pool.set_max_idle_conns(2).await; // 这个参数设置有效果

    let five_seconds = Duration::new(5, 0); // 支持
    pool.set_timeout(Option::from(five_seconds)).await;
    let five_seconds = Duration::new(20, 0); // 设置貌似没有效果啊，官方解答目前不支持
    pool.set_conn_max_lifetime(Option::from(five_seconds)).await;
    return rb;
}
```

**Comment by aohanhongzhi** [comment]
他是通过新建连接来解决的，不是在原有的链接基础上搞的。
![image](https://github.com/feihua/axum-admin/assets/37319319/6b8f3498-4705-44fe-8b8c-609f952a39da)
